[pytest]
DJANGO_SETTINGS_MODULE = mypet_project.settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --cov=mypet_project --cov-report=term-missing
testpaths = tests
pythonpath = .
