---
# Переменные VPS1 — Продакшн

app_dir: /opt/mypet01
app_user: depuser
app_repo: "https://github.com/riga1897/MyPet01.git"
app_branch: main

# Docker Compose
compose_file: docker-compose.prod.yml

# GeoIP (обновление через cron)
geoip_update_cron: "0 3 * * 0"   # каждое воскресенье в 3:00

# Prometheus exporters (порты)
node_exporter_port: 9100
postgres_exporter_port: 9187
nginx_exporter_port: 9113
haproxy_exporter_port: 9101
