# Generated by Django 6.0.1 on 2026-02-12 11:26

from typing import Any

import blog.models
import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_categories(apps: Any, schema_editor: Any) -> None:
    """Create initial categories and migrate existing Content."""
    Category = apps.get_model('blog', 'Category')
    Content = apps.get_model('blog', 'Content')
    yoga = Category.objects.create(name='Йога', slug='yoga', code='yoga')
    oils = Category.objects.create(name='Эфирные масла', slug='oils', code='oils')
    category_map = {'yoga': yoga, 'oils': oils}
    for content in Content.objects.all():
        old_category = content.category_old
        if old_category in category_map:
            content.category = category_map[old_category]
            content.save()


def reverse_categories(apps: Any, schema_editor: Any) -> None:
    """Reverse migration - convert back to string categories."""
    Category = apps.get_model('blog', 'Category')
    Content = apps.get_model('blog', 'Content')
    for content in Content.objects.all():
        if content.category_id:
            cat = Category.objects.get(pk=content.category_id)
            content.category_old = cat.code
            content.save()


def create_content_types_and_migrate(apps: Any, schema_editor: Any) -> None:
    ContentType = apps.get_model('blog', 'ContentType')
    Content = apps.get_model('blog', 'Content')
    video_type, _ = ContentType.objects.get_or_create(
        code='video', defaults={'name': 'Видео', 'slug': 'video', 'upload_folder': 'videos'},
    )
    photo_type, _ = ContentType.objects.get_or_create(
        code='photo', defaults={'name': 'Фото', 'slug': 'photo', 'upload_folder': 'photos'},
    )
    Content.objects.filter(old_content_type='video').update(content_type_new=video_type)
    Content.objects.filter(old_content_type='photo').update(content_type_new=photo_type)


def reverse_migration(apps: Any, schema_editor: Any) -> None:
    ContentType = apps.get_model('blog', 'ContentType')
    Content = apps.get_model('blog', 'Content')
    for content in Content.objects.select_related('content_type_new').all():
        if content.content_type_new:
            content.old_content_type = content.content_type_new.code
            content.save(update_fields=['old_content_type'])
    ContentType.objects.filter(code__in=['video', 'photo']).delete()


def migrate_content_type_to_m2m(apps: Any, schema_editor: Any) -> None:
    Content = apps.get_model('blog', 'Content')
    for content in Content.objects.filter(content_type__isnull=False):
        content.content_types.add(content.content_type)


def reverse_m2m_to_content_type(apps: Any, schema_editor: Any) -> None:
    Content = apps.get_model('blog', 'Content')
    for content in Content.objects.all():
        first_type = content.content_types.first()
        if first_type:
            content.content_type = first_type
            content.save(update_fields=['content_type'])

class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_comment_updated_at_post_updated_at_video_created_at_and_more'), ('blog', '0003_alter_comment_created_at_alter_post_created_at_and_more'), ('blog', '0004_alter_video_options_video_category_video_duration_and_more'), ('blog', '0005_rename_video_to_content'), ('blog', '0006_add_tags'), ('blog', '0007_add_category_model'), ('blog', '0008_remove_applies_to_all'), ('blog', '0009_add_tag_order'), ('blog', '0010_add_content_type_model'), ('blog', '0011_content_types_m2m'), ('blog', '0012_remove_contenttype_slug'), ('blog', '0013_make_code_blank'), ('blog', '0014_make_code_required'), ('blog', '0015_content_type_fk'), ('blog', '0016_remove_category_slug'), ('blog', '0017_remove_tag_slugs'), ('blog', '0018_content_categories_m2m'), ('blog', '0019_remove_content_duration'), ('blog', '0020_content_blog_conten_created_52a246_idx'), ('blog', '0021_add_pg_trgm_extension'), ('blog', '0022_add_updated_at_index')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
                ('applies_to_all', models.BooleanField(default=True, help_text='Если отмечено, группа будет видна для всех категорий', verbose_name='Применяется ко всем категориям')),
            ],
            options={
                'verbose_name': 'Группа тегов',
                'verbose_name_plural': 'Группы тегов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Слаг')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.taggroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['group', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
                ('code', models.CharField(help_text='Уникальный код для использования в коде (например: yoga, oils)', max_length=20, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='taggroup',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории, к которым относится эта группа тегов', related_name='tag_groups', to='blog.category', verbose_name='Категории'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(default='Без названия', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content_type', models.CharField(choices=[('video', 'Видео'), ('photo', 'Фото')], default='video', max_length=10, verbose_name='Тип')),
                ('video_file', models.FileField(blank=True, upload_to='videos/', verbose_name='Видео файл')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='Обложка')),
                ('duration', models.CharField(blank=True, help_text='Формат: MM:SS', max_length=10, verbose_name='Длительность')),
                ('category_old', models.CharField(choices=[('yoga', 'Йога'), ('oils', 'Эфирные масла')], default='yoga', max_length=10, verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='contents', to='blog.tag', verbose_name='Теги')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='blog.category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
        migrations.RunPython(
            code=populate_categories,
            reverse_code=reverse_categories,
        ),
        migrations.RemoveField(
            model_name='content',
            name='category_old',
        ),
        migrations.RemoveField(
            model_name='taggroup',
            name='applies_to_all',
        ),
        migrations.AlterField(
            model_name='taggroup',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым для применения ко всем категориям', related_name='tag_groups', to='blog.category', verbose_name='Категории'),
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['group', 'order', 'name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Меньшее значение = выше в списке', verbose_name='Порядок'),
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
                ('code', models.CharField(help_text='Уникальный код для использования в коде (например: video, photo, audio)', max_length=20, unique=True, verbose_name='Код')),
                ('upload_folder', models.CharField(default='content', help_text='Папка для сохранения файлов (например: videos, photos, audio)', max_length=100, verbose_name='Папка для файлов')),
            ],
            options={
                'verbose_name': 'Тип контента',
                'verbose_name_plural': 'Типы контента',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content_type',
            new_name='old_content_type',
        ),
        migrations.AddField(
            model_name='content',
            name='content_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='blog.contenttype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_file',
            field=models.FileField(blank=True, upload_to=blog.models.content_file_upload_path, verbose_name='Файл контента'),
        ),
        migrations.RunPython(
            code=create_content_types_and_migrate,
            reverse_code=reverse_migration,
        ),
        migrations.RemoveField(
            model_name='content',
            name='old_content_type',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content_type_new',
            new_name='content_type',
        ),
        migrations.AddField(
            model_name='content',
            name='content_types',
            field=models.ManyToManyField(blank=True, related_name='contents', to='blog.contenttype', verbose_name='Типы контента'),
        ),
        migrations.RunPython(
            code=migrate_content_type_to_m2m,
            reverse_code=reverse_m2m_to_content_type,
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contenttype',
            name='slug',
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='upload_folder',
            field=models.CharField(blank=True, help_text='Папка для сохранения файлов (по умолчанию = код)', max_length=100, verbose_name='Папка для файлов'),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='code',
            field=models.CharField(help_text='Генерируется автоматически из названия (можно изменить)', max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_types',
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='blog.contenttype', verbose_name='Тип контента'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, help_text='Генерируется автоматически из названия', max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='taggroup',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='contents', to='blog.category', verbose_name='Категории'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='duration',
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['created_at'], name='blog_conten_created_52a246_idx'),
        ),
        django.contrib.postgres.operations.TrigramExtension(
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='blog_conten_created_52a246_idx',
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-updated_at'], name='blog_conten_updated_b4bc78_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type'], name='blog_conten_content_f2fd2b_idx'),
        ),
    ]
