# Generated by Django 6.0.1 on 2026-01-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_created_at_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('yoga', 'Йога'), ('oils', 'Эфирные масла')], default='yoga', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, help_text='Формат: MM:SS', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Без названия', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
