# Generated by Django 6.0.1 on 2026-01-22 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_video_to_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Группа тегов',
                'verbose_name_plural': 'Группы тегов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('yoga', 'Йога'), ('oils', 'Эфирные масла')], default='yoga', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Видео'), ('photo', 'Фото')], default='video', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.CharField(blank=True, help_text='Формат: MM:SS', max_length=10, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='Без названия', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='Видео файл'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contents', to='blog.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.taggroup', verbose_name='Группа'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('group', 'name')},
        ),
    ]
