# Generated by Django 6.0.1 on 2026-01-22

import django.db.models.deletion
from django.db import migrations, models


def populate_categories(apps, schema_editor):
    """Create initial categories and migrate existing Content."""
    Category = apps.get_model('blog', 'Category')
    Content = apps.get_model('blog', 'Content')

    yoga = Category.objects.create(
        name='Йога',
        slug='yoga',
        code='yoga',
    )
    oils = Category.objects.create(
        name='Эфирные масла',
        slug='oils',
        code='oils',
    )

    category_map = {
        'yoga': yoga,
        'oils': oils,
    }

    for content in Content.objects.all():
        old_category = content.category_old
        if old_category in category_map:
            content.category = category_map[old_category]
            content.save()


def reverse_categories(apps, schema_editor):
    """Reverse migration - convert back to string categories."""
    Category = apps.get_model('blog', 'Category')
    Content = apps.get_model('blog', 'Content')

    for content in Content.objects.all():
        if content.category_id:
            cat = Category.objects.get(pk=content.category_id)
            content.category_old = cat.code
            content.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_add_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
                ('code', models.CharField(help_text='Уникальный код для использования в коде (например: yoga, oils)', max_length=20, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='taggroup',
            name='applies_to_all',
            field=models.BooleanField(default=True, help_text='Если отмечено, группа будет видна для всех категорий', verbose_name='Применяется ко всем категориям'),
        ),
        migrations.AddField(
            model_name='taggroup',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории, к которым относится эта группа тегов', related_name='tag_groups', to='blog.category', verbose_name='Категории'),
        ),
        migrations.RenameField(
            model_name='content',
            old_name='category',
            new_name='category_old',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='blog.category', verbose_name='Категория'),
        ),
        migrations.RunPython(populate_categories, reverse_categories),
        migrations.RemoveField(
            model_name='content',
            name='category_old',
        ),
    ]
