# Generated by Django 6.0.1 on 2026-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_add_category_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggroup',
            name='applies_to_all',
        ),
        migrations.AlterField(
            model_name='taggroup',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым для применения ко всем категориям', related_name='tag_groups', to='blog.category', verbose_name='Категории'),
        ),
    ]
