# Generated by Django 6.0.1 on 2026-01-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_applies_to_all'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['group', 'order', 'name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Меньшее значение = выше в списке', verbose_name='Порядок'),
        ),
    ]
