# Generated by Django 6.0.1 on 2026-01-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_add_tag_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым для применения ко всем категориям', related_name='contents', to='blog.category', verbose_name='Категории'),
        ),
    ]
