# Generated by Django 6.0.1 on 2026-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_change_category_to_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='photo_file',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Фото файл'),
        ),
    ]
