# Generated by Django 6.0.1 on 2026-01-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_content_types_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttype',
            name='slug',
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='upload_folder',
            field=models.CharField(blank=True, help_text='Папка для сохранения файлов (по умолчанию = код)', max_length=100, verbose_name='Папка для файлов'),
        ),
    ]
