# Generated by Django 6.0.1 on 2026-01-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_contenttype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='code',
            field=models.CharField(blank=True, help_text='Генерируется автоматически из названия (можно изменить)', max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
