# Generated by Django 6.0.1 on 2026-01-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_make_code_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='code',
            field=models.CharField(help_text='Генерируется автоматически из названия (можно изменить)', max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
