# Generated by Django 6.0.1 on 2026-01-22 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_make_code_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_types',
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='blog.contenttype', verbose_name='Тип контента'),
        ),
    ]
