# Generated by Django 6.0.1 on 2026-01-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_content_type_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, help_text='Генерируется автоматически из названия', max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
