# Generated by Django 6.0.1 on 2026-01-23 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='taggroup',
            name='slug',
        ),
    ]
