# Generated by Django 6.0.1 on 2026-01-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_tag_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='contents', to='blog.category', verbose_name='Категории'),
        ),
    ]
