# Generated by Django 6.0.1 on 2026-01-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_content_categories_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='duration',
        ),
    ]
