# Generated by Django 6.0.1 on 2026-01-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_content_duration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['created_at'], name='blog_conten_created_52a246_idx'),
        ),
    ]
