# Generated by Django 6.0.1 on 2026-01-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_add_pg_trgm_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='blog_conten_created_52a246_idx',
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-updated_at'], name='blog_conten_updated_b4bc78_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type'], name='blog_conten_content_f2fd2b_idx'),
        ),
    ]
